### SIGNIN
POST  http://localhost:1111/signin
Content-Type: application/json

{
    "username":"22AD063",
    "password":"0000"
}

### POST FORM
POST  http://localhost:1111/postform
Content-Type: application/json

{
    "fy_year": 2005,
    "month": "apr",
    "head_cat": "1",
    "sub_cat": "2",
    "date": "2005",
    "received_by":"dwdw",
    "particulars": "vsv",
    "bill_no": "sasv",
    "amount": "avvavd",
    "departments":"avava",
    "vehicles":"avavva"
}

### GENERATE PDF
GET http://localhost:1111/generatepdf/66a62e1d2ca106709800df55


### GET FORM
GET http://localhost:1111/getforms

### GET FORM BY ID
GET http://localhost:1111/getforms/66ddb0d900b39cdca053f3fa



### GET FY YEAR ONLY FROM FORM
GET http://localhost:1111/getfyyearoption

### GET MONTH ONLY FROM FORM
GET http://localhost:1111/getmonthoption

### GET HEAD CAT
GET http://localhost:1111/gethead_cat

### GET SUB CAT
GET http://localhost:1111/getsub_cat

### GET MONTH
GET http://localhost:1111/getmonth

### GET DEPARTMENT
GET http://localhost:1111/getdepartment

### GET EMPLOYEE
GET http://localhost:1111/getemployee

### GET VEHICLE
GET http://localhost:1111/getvehicle

### GET FY YEAR
GET http://localhost:1111/getfy_year

### GET FORM BY AMOUNT
GET http://localhost:1111/amount/11

### GET FORM BY PARTICULARS
GET http://localhost:1111/particulars/QEF

### GET FORM BY FY YEAR
GET http://localhost:1111/fy_year/2025

### GET FORM BY MONTH
GET http://localhost:1111/month/April

### GET FORM BY DATE
GET http://localhost:1111/date/2024-08-01

### GET FORM BY HEAD CAT NAME
GET http://localhost:1111/getFormByHeadCatName/Hiring Charges

### GET FORM BY SUB CAT NAME
GET http://localhost:1111/getFormBySubCatName/Bus Maintenance

### GET FORM BY VEHICLE ID
GET http://localhost:1111/getFormByVehicleID/1

### GET FORM BY EMPLOYEE ID
GET http://localhost:1111/getFormByEmployeeID/1

### GET FORM DATA BY FY YEAR AND MONTH 
GET http://localhost:1111/fy_year_month/2025/January

### TRUE FY YEAR ADMIN 
POST  http://localhost:1111/settruefyyear
Content-Type: application/json

{
    "fy_name":2026
}

### FLASE FY YEAR ADMIN 
POST  http://localhost:1111/setfalsefyyear
Content-Type: application/json

{
    "fy_name":2026
}

### TRUE MONTH ADMIN
POST  http://localhost:1111/setmonthtrue
Content-Type: application/json

{
    "month_name":"April"
}

### FALSE MONTH ADMIN 
POST  http://localhost:1111/setmonthfalse
Content-Type: application/json

{
    "month_name":"April"
}

### DELETE FORM

DELETE http://localhost:1111/erase/66c9fc7034ddba7a4167bc9d


###

PUT http://localhost:1111/modify
Content-Type: application/json

  {
    "_id": "66d51562ea1d60a318a1b03e",
    "fy_year": 2025,
    "month": "February",
    "head_cat": [
      {
        "_id": "66a632b82ca106709800df7e",
        "head_cat_id": 1,
        "head_cat_name": "Hiring Charges",
        "head_cat_status": true
      }
    ],
    "sub_cat": [
      {
        "_id": "66a631a12ca106709800df6e",
        "sub_cat_id": 1,
        "sub_cat_name": "Bus Maintenance",
        "head_cat_id": 4,
        "sub_cat_status": true,
        "spl_id": 0
      }
    ],
    "date": "2024-09-03",
    "received_by": [
      {
        "_id": "66a62e1d2ca106709800df56",
        "emp_id": 3,
        "emp_name": "Visvak Sena",
        "emp_status": "Active"
      }
    ],
    "particulars": "dharun",
    "bill_no": "2121",
    "departments": null,
    "amount": "10000",
    "vehicles": [
      {
        "_id": "66a630062ca106709800df6a",
        "vehicle_id": 2,
        "vehicle_name": "Bus 2",
        "vehicle_number": "M21",
        "vehicle_reg_number": "1111",
        "spl_id": 0
      }
    ],
    "files": "2121_2024-09-03_546.pdf",
    "uploads": [
      "consolidated-report (41).pdf"
    ],
    "__v": 0
  }

###
